
// src/data/galleryPhotos.js

export const galleryPhotos = [
  {
    id: 1,
    src: "/images/2025/arpanadi.jpg",
    title: "Farewell of Senior Dr. Arpana Saboo",
    tags: ["Lab Group", "Farewell", "IITKGP"],
    date: "2025-11-18",
  },
  {
    id: 2,
    src: "/images/2025/convocation.jpg",
    title: "M.Sc. Convocation, 2025",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "MSc", "Convocation"],
    date: "2025-07-15",
  },
  {
    id: 3,
    src: "/images/2025/convocation1.jpg",
    title: "MSc Convocation, 2025",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "MSc", "Convocation"],
    date: "2025-07-15",
  },
  {
    id: 4,
    src: "/images/2025/convocation2.jpg",
    title: "M.Sc. Convocation, 2025",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "MSc", "Convocation"],
    date: "2025-07-15",
  },
  {
    id: 5,
    src: "/images/2025/gr_1_home.jpg",
    title: "Research Group in Professor House",
    // desc: "Weekly discussion on QGNN and quantum control.",
    tags: ["Lab Group", "PhD"],
    date: "2025-11-02",
  },
  {
    id: 6,
    src: "/images/2025/hallday_mmm.jpg",
    title: "Hall Day Celebration 2025, @MMM",
    // desc: "Weekly discussion on QGNN and quantum control.",
    tags: ["Hall Day", "MMM", "MSc"],
    date: "2025-02-02",
  },
  {
    id: 7,
    src: "/images/2025/inhouse.jpg",
    title: "In House Symposium at IIT Kharagpur",
    // desc: "Weekly discussion on QGNN and quantum control.",
    tags: ["Lab Group", "Symposium","Phd"],
    date: "2025-09-04",
  },
  {
    id: 8,
    src: "/images/2023/mmm.jpg",
    title: "First Day at IIT Kharagpur near MMM Hall",
    // desc: "Weekly discussion on QGNN and quantum control.",
    tags: ["MMM", "MSc"],
    date: "2023-09-04",
  },
  {
    id: 9,
    src: "/images/2025/convocation3.JPG",
    title: "M.Sc. Convocation, 2025",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "MSc", "convocation"],
    date: "2025-07-15",
  },
  {
    id: 10,
    src: "/images/2025/indoml_1.jpeg",
    title: "IndoML 2025 @BITS Pilani Hyderabad",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["Symposium", "IndoML '25", "Hyderabad", "BITS"],
    date: "2025-12-19",
  },
  {
    id: 11,
    src: "/images/2025/indoml_2.jpeg",
    title: "IndoML 2025 @BITS Pilani Hyderabad",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["Symposium", "IndoML '25", "Hyderabad", "BITS"],
    date: "2025-12-19",
  },
  {
    id: 12,
    src: "/images/2025/bits.jpeg",
    title: "BITS Pilani Hyderabad Auditorium",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IndoML '25", "BITS", "Hyderabad"],
    date: "2025-12-18",
  },
  {
    id: 13,
    src: "/images/2025/hyderabad_1.jpeg",
    title: "Charminar, Hyderabad",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["Hyderabad"],
    date: "2025-12-20",
  },
  {
    id: 14,
    src: "/images/2025/indoml_3.jpeg",
    title: "IndoML '25 Group Photo",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IndoML '25", "BITS", "Hyderabad"],
    date: "2025-12-19",
  },
  {
    id: 15,
    src: "/images/2023/mmm2.jpg",
    title: "MSc Days near Nehru Museum ",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["MSc", "IITKGP"],
    date: "2023-10-19",
  },
  {
    id: 16,
    src: "/images/2025/convocation_mp.JPG",
    title: "M.Sc. Convocation, 2025",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["MSc", "convocation", "IITKGP"],
    date: "2025-07-15",
  },
  {
    id: 17,
    src: "/images/2025/freshers.JPG",
    title: "Freshers as Research Scholar @KGP",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP"],
    date: "2025-10-31",
  },
  {
    id: 18,
    src: "/images/2025/gr1.jpeg",
    title: "SM Group",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "Lab Group"],
    date: "2025-10-31",
  },
  {
    id: 19,
    src: "/images/2023/im2.jpg",
    title: "Pt. Madan Mohan Malaviya Hall of Residence",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "MMM", "MSc"],
    date: "2023-09-04",
  },
  {
    id: 20,
    src: "/images/2026/NSD26.jpg",
    title: "National Science Day @IIT Kharagpur",
    // desc: "M.Sc. Convocation at IIT Kharagpur",
    tags: ["IITKGP", "Science Day", "PhD"],
    date: "2026-02-28",
  },
  {
    id: 21,
    src: "/images/2026/Uluberia_seminar.jpeg",
    title: "State-Level Seminar on AI Horizons @ Uluberia College",
    // desc: "Visited Uluberia College as Speaker ",
    tags: ["Uluberia College", "Seminar", "PhD"],
    date: "2026-02-05",
  },
  
  // Add more images above
];
